env: prod
imagePullSecret: ecr-secret

replicaCount: 2

image:
  repository: 431538665162.dkr.ecr.ap-northeast-2.amazonaws.com/backend
  tag: "latest"

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: prod.dongkyu.cloud
